# Generated by Django 3.2.16 on 2022-11-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='point_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.IntegerField()),
                ('longitud', models.IntegerField()),
            ],
        ),
    ]
